dist: trusty
sudo: false

language: node_js

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install

before_install:
  - export NG_CLI_ANALYTICS=ci

script:
  - npm run lint
  - npm run coverage
