name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  TZ: 'Europe/Brussels'
  HUSKY_SKIP_INSTALL: 1
  NG_CLI_ANALYTICS: 'ci'

jobs:
  test:
    name: Build and test on Node.js ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['16']
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test
